// <auto-generated />
using System;
using Contacts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contacts.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210619232922_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contacts.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "454, Laurel St, California",
                            Name = "Angeline",
                            Note = "School Friend",
                            PhoneNumber = 9910456545L
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "589, Kings St, Texas",
                            Name = "Rajakumar",
                            Note = "Neighbour",
                            PhoneNumber = 8945786231L
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "111, Sagewood St, Iowa",
                            Name = "Jeshlin",
                            Note = "School Teacher",
                            PhoneNumber = 8521463335L
                        },
                        new
                        {
                            ContactId = 4,
                            Address = "785, Samsung St, Iowa",
                            Name = "Ferryn",
                            Note = "Mercy Doctor",
                            PhoneNumber = 5152202323L
                        },
                        new
                        {
                            ContactId = 5,
                            Address = "412, Hickman St, California",
                            Name = "Braydon",
                            Note = "Colleague",
                            PhoneNumber = 9005157723L
                        },
                        new
                        {
                            ContactId = 6,
                            Address = "155, Milton Ave, California",
                            Name = "Jacklin",
                            Note = "Relative",
                            PhoneNumber = 5152124544L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
